#!/bin/bash

SCRIPTS_DIRECTORY="$(dirname "${0}")"
ANIMALS_FILE="${SCRIPTS_DIRECTORY}/../resources/animals.txt"
ANIMAL_NAME=$(shuf -n 1 "${ANIMALS_FILE}" | tr "[:upper:]" "[:lower:]" | tr -d " ")

echo "${ANIMAL_NAME}"
