#!/bin/bash

source bash-color-scheme

echo "Platform Initialization"
echo ""
echo "  Company Name................: $(show_value "${COMPANY_NAME}")"
echo "  Platform Name...............: $(show_value "${PLATFORM_NAME}")"
echo "  Platform Region.............: $(show_value "${PLATFORM_REGION}")"
echo "  Source Directory............: $(show_file_status "${SOURCE_DIRECTORY}")"
echo ""
