#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

red() {
  echo "${RED}${1}${NC}"
}

green() {
  echo "${GREEN}${1}${NC}"
}

yellow() {
  echo "${YELLOW}${1}${NC}"
}

show_file_status() {
  FILE_NAME=$1

  STATUS_UNDEFINED=$(yellow   " undefined ")
  STATUS_NOT_FOUND=$(red      " not found ")
  STATUS_CREATED=$(  green    " created   ")

  STATUS="${STATUS_NOT_FOUND}"

  if [ -z "${FILE_NAME}" ]; then
      STATUS="${STATUS_UNDEFINED}"
  else
    if [ -e "${FILE_NAME}" ]; then
      STATUS="${STATUS_CREATED}"
    fi
  fi

  STATUS=$(printf "%*s\n" $(((${#STATUS} + 20)/2)) "${STATUS}")

  echo -e "[${STATUS}] ${FILE_NAME}"
}

echo ""
echo "Platform Parameters"
echo ""
echo "  PLATFORM_NAME...............: ${PLATFORM_NAME}"
echo "  RESOURCE_GROUP_NAME.........: ${RESOURCE_GROUP_NAME}"
echo "  PLATFORM_FOUNDATION_REGION..: ${PLATFORM_FOUNDATION_REGION}"
echo "  ARM_SUBSCRIPTION_ID.........: ${ARM_SUBSCRIPTION_ID}"
echo "  ARM_TENANT_ID...............: ${ARM_TENANT_ID}"
echo "  ARM_CLIENT_ID...............: ${ARM_CLIENT_ID}"
echo "  ARM_CLIENT_SECRET...........: ${#ARM_CLIENT_SECRET}"
echo "  ARM_STORAGE_ACCOUNT_NAME....: ${ARM_STORAGE_ACCOUNT_NAME}"
echo "  ARM_ACCESS_KEY..............: ${#ARM_ACCESS_KEY}"
echo "  SOURCE_FOLDER...............: $(show_file_status "${SOURCE_FOLDER}")"
echo "  OUTPUT_FOLDER...............: $(show_file_status "${OUTPUT_FOLDER}")"
echo "  STORAGE_ACCOUNT_PARAMETERS..: $(show_file_status "${OUTPUT_FOLDER}/backend.conf")"
echo "  STORAGE_ACCOUNT_CREDENTIALS.: $(show_file_status "${OUTPUT_FOLDER}/credentials.conf")"
echo "  ARM_PROVIDER_BACKEND........: $(show_file_status "${OUTPUT_FOLDER}/provider.tf")"
echo "  FOUNDATION_SOURCE_FOLDER....: $(show_file_status "${AZURE_PLATFORM_FOUNDATION_SOURCE_FOLDER}")"
echo ""
