#!/bin/bash

terraform init -reconfigure

terraform plan

terraform apply -auto-approve

export ARM_STORAGE_ACCOUNT_NAME=$(terraform output --raw platform_storage_account_name)
export ARM_ACCESS_KEY=$(terraform output --raw platform_storage_account_primary_access_key)

envsubst < ../templates/credentials.conf > ../output/credentials.conf

echo ""
echo "Platform Parameters"
echo ""
echo "  ARM_SUBSCRIPTION_ID.........: ${ARM_SUBSCRIPTION_ID}"
echo "  ARM_TENANT_ID...............: ${ARM_TENANT_ID}"
echo "  ARM_CLIENT_ID...............: ${ARM_CLIENT_ID}"
echo "  ARM_CLIENT_SECRET...........: ${#ARM_CLIENT_SECRET}"
echo "  ARM_STORAGE_ACCOUNT_NAME....: ${ARM_STORAGE_ACCOUNT_NAME}"
echo "  ARM_ACCESS_KEY..............: ${#ARM_ACCESS_KEY}"
echo "  STORAGE_ACCOUNT_PARAMETERS..: ../output/backend.conf"
echo "  STORAGE_ACCOUNT_CREDENTIALS.: ../output/credentials.conf"
echo ""
